"""Cấu hình cố định cho ứng dụng giám sát miền Trung."""

APP_NAME = "TOMS SLA MT"
APP_SLUG = "TOMS-SLA-MT"
APP_DATA_ENV = "TOMS_SLA_MT_DATA_DIR"
TELEGRAM_TOKEN_ENV = "TOMS_SLA_MT_TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ENV = "TOMS_SLA_MT_TELEGRAM_GROUP_CHAT_ID"
UNIT_LABEL = "Phòng HTKH Miền Trung (VIP 3)"
